version: '3.8'

services:
  # Serviço para a aplicação principal
  app:
    build: .
    # Mapeia a porta 3000 do contêiner para a porta 3000 do host
    ports:
      - "3000:3000"
    # Monta volumes para persistência de dados e sincronização de arquivos
    volumes:
      - .:/app             # Monta o diretório atual no diretório /app do contêiner
      - /app/node_modules  # Monta um volume separado para node_modules para evitar sobrescrita
    # Comando para iniciar a aplicação
    command: npm run dev
    # Variáveis de ambiente passadas para o contêiner
    environment:
      GEMINI_API_KEY: ${GEMINI_API_KEY}  # Chave da API do Gemini
      DATABASE_URL: ${DATABASE_URL}     # URL de conexão com o banco de dados
      PORT: 3001                        # Porta exposta pela aplicação no contêiner
    # Configura o comportamento de reinício do contêiner
    restart: unless-stopped

  # Serviço para o banco de dados PostgreSQL
  db:
    image: postgres:latest
    # Variáveis de ambiente para configuração do PostgreSQL
    environment:
      POSTGRES_USER: user              # Usuário padrão do PostgreSQL
      POSTGRES_PASSWORD: password      # Senha para o usuário do PostgreSQL
      POSTGRES_DB: mydatabase          # Nome do banco de dados a ser criado
    # Mapeia a porta 5432 do contêiner para a porta 5432 do host
    ports:
      - "5432:5432"
    # Monta um volume para persistência dos dados do banco de dados
    volumes:
      - postgres-data:/var/lib/postgresql/data

# Definição do volume para persistência de dados do PostgreSQL
volumes:
  postgres-data:
